
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.4
 * Tue Aug 01 19:48:08 ART 2023
 * Generated source version: 3.5.4
 */

@XmlRootElement(name = "getList", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getList", namespace = "http://ws.das.ubp.edu.ar/")

public class GetList {


}

